services:
  postgres:
    image: postgres:16
    container_name: useful-git-info-postgres
    restart: unless-stopped
    ports:
      - '55432:5432'
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: useful_git_info
    volumes:
      - useful_git_info_pgdata:/var/lib/postgresql/data

volumes:
  useful_git_info_pgdata:
